version: '3'
services:
  collectd:
    image: collectd:sddj
    ports:
      - '127.0.0.1:10003:8888'
    volumes:
      - ./collectd.d:/etc/collectd.d
      - ./shared.d:/shared.d
  rabbitmq:
    image: rabbitmq:3.7.5
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '127.0.0.1:10002:5672'
  redis:
    image: redis:4.0.9
    ports:
      - '127.0.0.1:10001:6379'
  minemeld:
    image: minemeld
    environment:
      - MINEMELD_PROTOTYPE_PATH=/etc/collectd.d/prototypes
    links:
      - rabbitmq
      - redis
    volumes:
      - ./collectd.d:/etc/collectd.d
  nginx:
    image: nginx:1.14.0
    links:
      - minemeld
