nodes:
  spamhaus_DROP:
    output: true
    prototype: spamhaus.DROP
#  spamhaus_EDROP:
#    output: true
#    prototype: spamhaus.EDROP
#  dshield_blocklist:
#    output: true
#    prototype: dshield.block
#  wlWhiteListIPv4:
#    inputs: []
#    output: true
#    prototype: stdlib.listIPv4Generic
#  inboundaggregator:
#    inputs:
#    - spamhaus_DROP
#    - spamhaus_EDROP
#    - dshield_blocklist
#    - wlWhiteListIPv4
#    output: true
#    prototype: stdlib.aggregatorIPv4Inbound
#  inboundfeedhc:
#    inputs:
#    - inboundaggregator
#    output: false
#    prototype: stdlib.feedHCGreen
#  inboundfeedlc:
#    inputs:
#    - inboundaggregator
#    output: false
#    prototype: stdlib.feedLCGreen
#  inboundfeedmc:
#    inputs:
#    - inboundaggregator
#    output: false
#    prototype: stdlib.feedMCGreen
fabric:
  class: AMQP
  config:
    host: 127.0.0.1:10002
    num_connections: 50
    priority: -2
mgmtbus:
  transport:
    class: AMQP
    config:
      host: 127.0.0.1:10002
      num_connections: 50
      priority: -2
  master:
    REDIS_URL: redis://127.0.0.1:10001/0
    COLLECTD_SOCKET: tcp://127.0.0.1:10003
  slave:
