fabric:
  class: ZMQRedis
  config:
    redis_url: redis://127.0.0.1:10001
    zmq_url: ipc:///tmp/minemeld-{1}
mgmtbus:
  master:
    COLLECTD_SOCKET: tcp://127.0.0.1:10003
    REDIS_URL: redis://127.0.0.1:10001
  slave: null
  transport:
    class: ZMQRedis
    config:
      redis_url: redis://127.0.0.1:10001
      zmq_url: ipc:///tmp/minemeld-{1}
nodes:
  PhishTank:
    inputs: []
    output: true
    prototype: hailataxii.guest_phishtank_com
  spamhaus_DROP:
    output: true
    prototype: spamhaus.DROP
